name: Patch Last Modified Timestamp

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  patch:
    name: Patch Last Modified
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0 # fetch full history

      - name: Patch last-updated field
        run: |
          # Get list of .txt files changed in last commit (ignoring trivial changes)
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD -- '*.txt')

          for f in $CHANGED_FILES; do
            # Make sure file still exists (not deleted)
            if [[ -f "$f" ]]; then
              # Get last commit date for that file
              COMMIT_DATE=$(git log -1 --format=%cD -- "$f")

              # Replace whatever is after "! Last modified: " with commit date
              if sed --version >/dev/null 2>&1; then
                sed -ir "0,/^! Last modified: /s|^\(! Last modified: \).*|\1$COMMIT_DATE|" "$f"
              else
                sed -i '' "0,/^! Last modified: /s|^\(! Last modified: \).*|\1$COMMIT_DATE|" "$f"
              fi
            fi
          done

      - name: Commit changes (if any)
        run: |
          if [[ -n $(git diff) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -u
            git commit -m "Update modified filter lists with last commit timestamp"
            git push origin main
          fi
